apiVersion: apps/v1
kind: Deployment
metadata:
  name: groww-deployment
  labels:
    first: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: groww-container
          image: mshaan/groww:v1.0.0
          ports:
            - containerPort: 5005
      