apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_User: {{ .Values.secret.dbUser }}
  DB_Pass: {{ .Values.secret.dbPass }}