apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  api-token: {{ .Values.secrets.apiToken | b64enc | quote }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}